---
driver:
  name: docker
  use_sudo: false

busser:
  ruby_bindir: '/usr/bin'

provisioner:
  name: chef_zero
  chef_client_path: '/usr/bin/chef-client'

platforms:
  - name: arch
    driver_config:
      image: 'logankoester/archlinux-chef'
      platform: arch
      disable_upstart: true
      require_chef_omnibus: false
      provision_command:
        - pacman -Sy
        - pacman -S --noconfirm --needed supervisor git
        - rm /etc/gemrc
      run_command: 'sh -c "/usr/sbin/sshd -o UseDNS=no -o UsePAM=no -o PasswordAuthentication=yes && /usr/sbin/supervisord -c /etc/supervisord.conf -n"'

suites:
  - name: default
    driver_config:
      hostname: default
    run_list:
      - 'recipe[supervisor]'
      - 'recipe[ldk-mongodb]'
    data_bags_path: 'test/integration/data_bags'
    attributes:
      mongodb:
        supervisor: true
  - name: consul
    driver_config:
      hostname: consul
    run_list:
      - 'recipe[supervisor]'
      - 'recipe[consul-template]'
      - 'recipe[ldk-mongodb]'
      - 'recipe[ldk-mongodb::consul-template]'
    data_bags_path: 'test/integration/data_bags'
    attributes:
      mongodb:
        supervisor: true
      consul_template:
        install_method: 'source'
        init_style: 'supervisor'
        service_user: 'root'
        service_group: 'root'
        template_mode: '0755'
        config:
          consul: '127.0.0.1:8500'
          max_stale: '10m'
          ssl:
            enabled: false
            verify: false
          retry: '10s'
